export const AUSTRALIAN_STATES = [
  { value: 'NSW', label: 'New South Wales' },
  { value: 'VIC', label: 'Victoria' },
  { value: 'QLD', label: 'Queensland' },
  { value: 'WA', label: 'Western Australia' },
  { value: 'SA', label: 'South Australia' },
  { value: 'TAS', label: 'Tasmania' },
  { value: 'ACT', label: 'Australian Capital Territory' },
  { value: 'NT', label: 'Northern Territory' }
] as const 

// Dance Styles Constants
export const DANCE_STYLES = [
  'Bachata',
  'Salsa', 
  'Kizomba',
  'Zouk',
  'Reggaeton',
  'Heels',
  'Pole Dance',
  'Latin Beat',
  'HipHop',
  'Mambo',
  'Dominican Bachata',
  'Sensual Bachata',
  'Bachata Moderna',
  'Cuban Salsa',
  'Chacha',
  'Rumba',
  'Merengue',
  'Tango',
  'Afrobeats',
  'Taraxo',
  'Choreography',
  'Ballroom',
  'Twerk',
  'Jazz',
  'Contemporary',
  'Bachazouk',
  'Bachata Influence',
  'All',
  'Other'
] as const

export type DanceStyle = typeof DANCE_STYLES[number]

// Country Constants
export const COUNTRIES = [
  'Australia',
  'New Zealand',
  'United States',
  'Canada',
  'United Kingdom',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Slovakia',
  'Slovenia',
  'Croatia',
  'Serbia',
  'Romania',
  'Bulgaria',
  'Greece',
  'Portugal',
  'Ireland',
  'Iceland',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Japan',
  'South Korea',
  'China',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Indonesia',
  'India',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Mexico',
  'Costa Rica',
  'Panama',
  'Venezuela',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Ecuador',
  'South Africa',
  'Egypt',
  'Morocco',
  'Tunisia',
  'Algeria',
  'Libya',
  'Sudan',
  'Ethiopia',
  'Kenya',
  'Uganda',
  'Tanzania',
  'Nigeria',
  'Ghana',
  'Senegal',
  'Ivory Coast',
  'Cameroon',
  'Gabon',
  'Congo',
  'DR Congo',
  'Angola',
  'Zambia',
  'Zimbabwe',
  'Botswana',
  'Namibia',
  'Mozambique',
  'Madagascar',
  'Mauritius',
  'Seychelles',
  'Comoros',
  'Mayotte',
  'Reunion',
  'Other'
] as const

export type Country = typeof COUNTRIES[number] 