export const AUSTRALIAN_STATES = [
  { value: 'NSW', label: 'New South Wales' },
  { value: 'VIC', label: 'Victoria' },
  { value: 'QLD', label: 'Queensland' },
  { value: 'WA', label: 'Western Australia' },
  { value: 'SA', label: 'South Australia' },
  { value: 'TAS', label: 'Tasmania' },
  { value: 'ACT', label: 'Australian Capital Territory' },
  { value: 'NT', label: 'Northern Territory' }
] as const 

// Dance Styles Constants
export const DANCE_STYLES = [
  'Bachata',
  'Salsa', 
  'Kizomba',
  'Zouk',
  'Reggaeton',
  'Heels',
  'Pole Dance',
  'Latin Beat',
  'HipHop',
  'Mambo',
  'Dominican Bachata',
  'Sensual Bachata',
  'Bachata Moderna',
  'Cuban Salsa',
  'Chacha',
  'Rumba',
  'Merengue',
  'Tango',
  'Afrobeats',
  'Taraxo',
  'Choreography',
  'Ballroom',
  'Twerk',
  'Jazz',
  'Contemporary',
  'Bachazouk',
  'Bachata Influence',
  'All',
  'Other'
] as const

export type DanceStyle = typeof DANCE_STYLES[number]

// Country Constants
export const COUNTRIES = [
  'Australia',
  'New Zealand',
  'United States',
  'Canada',
  'United Kingdom',
  'Spain',
  'France',
  'Germany',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Greece',
  'Portugal',
  'Ireland',
  'Iceland',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Slovenia',
  'Slovakia',
  'Croatia',
  'Serbia',
  'Bosnia and Herzegovina',
  'Montenegro',
  'North Macedonia',
  'Albania',
  'Kosovo',
  'Moldova',
  'Ukraine',
  'Belarus',
  'Russia',
  'Georgia',
  'Armenia',
  'Azerbaijan',
  'Turkey',
  'Israel',
  'Lebanon',
  'Syria',
  'Jordan',
  'Iraq',
  'Iran',
  'Kuwait',
  'Saudi Arabia',
  'Bahrain',
  'Qatar',
  'United Arab Emirates',
  'Oman',
  'Yemen',
  'Egypt',
  'Libya',
  'Tunisia',
  'Algeria',
  'Morocco',
  'South Africa',
  'Kenya',
  'Nigeria',
  'Ghana',
  'Ethiopia',
  'Uganda',
  'Tanzania',
  'Rwanda',
  'Democratic Republic of the Congo',
  'Angola',
  'Zambia',
  'Zimbabwe',
  'Botswana',
  'Namibia',
  'Mozambique',
  'Madagascar',
  'Mauritius',
  'Seychelles',
  'China',
  'Japan',
  'South Korea',
  'North Korea',
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Bhutan',
  'Maldives',
  'Afghanistan',
  'Kazakhstan',
  'Uzbekistan',
  'Kyrgyzstan',
  'Tajikistan',
  'Turkmenistan',
  'Mongolia',
  'Thailand',
  'Vietnam',
  'Cambodia',
  'Laos',
  'Myanmar',
  'Malaysia',
  'Singapore',
  'Indonesia',
  'Philippines',
  'Brunei',
  'East Timor',
  'Taiwan',
  'Hong Kong',
  'Macau',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Mexico',
  'Costa Rica',
  'Panama',
  'Venezuela',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Ecuador',
  'Other'
] as const

export type Country = typeof COUNTRIES[number] 